// <auto-generated />
using LinqExamples;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LinqExamples.Migrations
{
    [DbContext(typeof(LinqDbContext))]
    partial class LinqDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LinqExamples.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Location = "New York",
                            Name = "IT"
                        },
                        new
                        {
                            ID = 2,
                            Location = "London",
                            Name = "HR"
                        },
                        new
                        {
                            ID = 3,
                            Location = "Sydney",
                            Name = "Payroll"
                        });
                });

            modelBuilder.Entity("LinqExamples.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("Decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentID = 1,
                            FirstName = "Mark",
                            Gender = "Male",
                            LastName = "Hasting",
                            Salary = 60000.0m
                        },
                        new
                        {
                            ID = 2,
                            DepartmentID = 3,
                            FirstName = "Steve",
                            Gender = "Male",
                            LastName = "Pound",
                            Salary = 45000.0m
                        },
                        new
                        {
                            ID = 3,
                            DepartmentID = 1,
                            FirstName = "Ben",
                            Gender = "Male",
                            LastName = "Hoskins",
                            Salary = 70000.0m
                        },
                        new
                        {
                            ID = 4,
                            DepartmentID = 2,
                            FirstName = "Philp",
                            Gender = "Male",
                            LastName = "Hastings",
                            Salary = 45000.0m
                        },
                        new
                        {
                            ID = 5,
                            DepartmentID = 2,
                            FirstName = "Mary",
                            Gender = "Female",
                            LastName = "Lambeth",
                            Salary = 30000.0m
                        },
                        new
                        {
                            ID = 6,
                            DepartmentID = 3,
                            FirstName = "Valarie",
                            Gender = "Female",
                            LastName = "Vikings",
                            Salary = 35000.0m
                        },
                        new
                        {
                            ID = 7,
                            DepartmentID = 1,
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Stanmore",
                            Salary = 80000.0m
                        });
                });

            modelBuilder.Entity("LinqExamples.Employee", b =>
                {
                    b.HasOne("LinqExamples.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LinqExamples.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
